import { ArrowDown, ArrowUpRight, BrainCircuit, Database, Github, Linkedin, Mail, Sparkles, Trophy, Cpu, Activity, Radio, Server, ShieldCheck } from "lucide-react";
import { Navbar } from "@/components/navbar";

const projects = [
  { n: "01", title: "Hand Assessment AI", type: "Computer Vision · Healthcare", desc: "Video/webcam assessment for elderly rehabilitation. Tracks 21 hand landmarks, extracts speed/accuracy/quality features, compares left/right symmetry and estimates hand dominance and Learned Non-Use risk.", stack: "Python · OpenCV · MediaPipe · NumPy · SciPy · scikit-learn · Streamlit", href: "https://github.com/thanithpol2545/ai-vibe-coding-digital-aiding-4-aging-hackathon" },
  { n: "02", title: "Moon Walk — Smart Cane AIoT", type: "AIoT · Hackathon · Assistive Tech", desc: "1st Runner Up at the WellSense AIoT Hackathon. A clip-on sensing module turns an ordinary cane or walker into a smart mobility monitor for gait rhythm, balance and cane-load feedback.", stack: "Arduino Nano 33 BLE · LSM9DS1 IMU · Pressure Sensing · BLE · Arduino UNO Q · Supabase", href: "#moonwalk", featured: true },
  { n: "03", title: "Air Pollution & Fire Hotspots Analysis", type: "Data Science · Research", desc: "Thailand analysis connecting VIIRS hotspot activity with PM2.5, PM10, CO, NO2, SO2 and O3 using time-series, regional/provincial analysis, Pearson R, R² and p-values.", stack: "Python · Pandas · SciPy · scikit-learn · Excel · QGIS", href: "https://github.com/thanithpol2545/Combustion-Air-Pollutant-and-Fire-Hotspots-Analysis-in-Thailand" },
  { n: "04", title: "Nitrification Dynamics Simulator", type: "Environmental Engineering · Web", desc: "Interactive simulation project translating environmental-engineering process equations and nitrification dynamics into a usable web experience.", stack: "Python · Simulation · Web · Environmental Engineering", href: "https://github.com/thanithpol2545/nitrification-dynamics-simulator" },
  { n: "05", title: "Nan Flourish — Beyond Seasons", type: "Hackathon · Product", desc: "Hackathon project focused on building a digital experience around Nan and connecting technology, local context and user-facing product design.", stack: "Web · Product Design · Data · Hackathon", href: "https://sanae-nan.vercel.app" },
  { n: "06", title: "Siam Hack 4 Super AI", type: "AI · Hackathon", desc: "Interactive web app built with Google AI Studio / Gemini during the Siam Hack 4 Super AI hackathon.", stack: "Google AI Studio · Gemini · Vite · React", href: "https://sanae-siam-hack-4-super-ai.vercel.app" },
];

const skills = [
  ["LLM & AI Applications", "RAG · Hybrid Retrieval · Reranking · Agentic / Tool Use · Prompt Engineering · Guardrails · Thai NLP · LLM Evaluation"],
  ["ML & Deep Learning", "PyTorch · Hugging Face Transformers · scikit-learn · LightGBM · XGBoost · Computer Vision · OCR · ASR · VQA · Time Series"],
  ["Data Engineering", "Python · SQL · Pandas · PySpark · ETL · Delta Lake · Medallion Architecture · Databricks · Lakeflow · Jobs · Unity Catalog"],
  ["Product & Development", "Next.js · React · TypeScript · Tailwind CSS · Streamlit · Power BI · Git · GitHub · Docker · Linux"],
  ["AIoT & Edge", "Arduino · Arduino UNO Q · Raspberry Pi · Jetson Nano · IMU · BLE · IoT sensor networks · Edge AI"],
  ["Engineering & Sustainability", "GHG Protocol · Scope 1–3 · CFO · CFP · ESG · QGIS · AutoCAD · Environmental Engineering"],
];

const experiences = [
  ["2025 — Present", "Business Development Associate", "Zeroboard (Thailand) Co., Ltd.", "Supported ESG and carbon-accounting projects, GHG Protocol Scope 1–3, Carbon Footprint for Organization and Product, and data-driven sustainability initiatives."],
  ["2025", "Digital & Sustainability Officer", "MDT Manufacturing", "Built barcode/data-collection workflows, centralized ISO data, supported CFO/CFP reporting and KPI dashboards."],
  ["2024", "Site Engineer Intern", "Origin Property Public Co.", "Supported construction-site engineering and building-system coordination at The Origin Plug & Play Ramintra."],
  ["2022", "Research Assistant", "Kasetsart University · Faculty of Agriculture", "Worked with IoT sensors and experimental data for indoor smart-farming research."],
];

const awards = [
  ["Top 21", "AI Benchmark 2026 · LLM Trustworthiness Challenge", "11th place · Team E20 · 91 teams / 194 participants"],
  ["1st Runner Up", "WellSense AIoT Hackathon · Super AI Engineer S6", "", "moonwalk-award.jpg"],
  ["180 / 10,000+", "Super AI Engineer Season 6 · AIAT", "Selected for the national AI engineering program"],
  ["Associate Engineer", "Council of Engineers Thailand", "Environmental Engineering professional license"],
];

const moonwalkLayers = [
  ["01", "Device Layer", "Arduino Nano 33 BLE + LSM9DS1 IMU reads accelerometer and gyroscope signals and computes initial features such as acceleration norm, gyro norm and walking phase.", Activity],
  ["02", "Communication Layer", "BLE payload transmits IMU values, timestamp, acceleration, gyroscope, normalized features and phase data at approximately 50 ms intervals.", Radio],
  ["03", "Edge / Gateway Layer", "Arduino UNO Q receives, parses, validates, displays and locally logs the BLE stream before forwarding data downstream.", Cpu],
  ["04", "Processing & Service", "Data ingestion, phase classification, feature extraction, session management and rule-based event detection create higher-level mobility insights.", Server],
  ["05", "Storage & Application", "Supabase provides database/session storage and API integration for dashboards, clinician/caregiver views and rehabilitation progress monitoring.", Database],
];

function Label({ children }: { children: React.ReactNode }) { return <p className="mb-4 text-[11px] font-bold uppercase tracking-[.22em] text-cyan-300">{children}</p>; }
function LinkButton({ href, children = "View project" }: { href: string; children?: React.ReactNode }) { return <a href={href} target={href.startsWith("http") ? "_blank" : undefined} rel={href.startsWith("http") ? "noreferrer" : undefined} className="inline-flex items-center gap-1.5 text-xs font-semibold text-cyan-200 transition hover:text-white">{children}<ArrowUpRight size={14}/></a>; }

export default function Home() {
  return <main id="top" className="noise relative overflow-hidden"><Navbar /><div className="pointer-events-none absolute inset-x-0 top-0 h-[760px] grid-fade" /><div className="pointer-events-none absolute -top-48 left-1/2 h-[560px] w-[560px] -translate-x-1/2 rounded-full bg-cyan-400/[.07] blur-[120px]" />
    <section className="relative mx-auto flex min-h-screen max-w-6xl items-center px-5 pb-20 pt-32 lg:px-8"><div className="grid w-full gap-14 lg:grid-cols-[1.35fr_.65fr] lg:items-center"><div>
      <div className="mb-7 inline-flex items-center gap-2 rounded-full border border-cyan-300/15 bg-cyan-300/[.05] px-3 py-1.5 text-[11px] font-semibold text-cyan-100"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-400"/> AI / ML · DATA · AIoT · FULL STACK</div>
      <h1 className="max-w-4xl font-display text-5xl font-bold leading-[.98] tracking-[-.055em] text-white sm:text-7xl lg:text-[88px]">Building intelligent products <span className="bg-gradient-to-r from-cyan-300 via-sky-300 to-violet-300 bg-clip-text text-transparent">from data to deployment.</span></h1>
      <p className="mt-8 max-w-2xl text-base leading-7 text-slate-400 sm:text-lg">I&apos;m Thanithpol Thiramongkolchai — an Environmental Engineer turned AI/ML Engineer. I build LLM/RAG systems, agentic pipelines, computer-vision applications, data platforms and AIoT products.</p>
      <div className="mt-9 flex flex-wrap gap-3"><a href="#projects" className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-bold text-slate-950 transition hover:-translate-y-0.5 hover:bg-cyan-100">Explore my work <ArrowDown size={16}/></a><a href="mailto:thanipol2545@gmail.com" className="inline-flex items-center gap-2 rounded-full border border-white/10 px-5 py-3 text-sm font-semibold text-white transition hover:-translate-y-0.5 hover:border-cyan-300/30"><Mail size={16}/> Contact</a></div>
      <div className="mt-14 grid max-w-2xl grid-cols-2 gap-6 border-t border-white/[.08] pt-6 sm:grid-cols-4">{[["11th","AI Benchmark 2026"],["Top 21","of 91 teams"],["1st Runner Up","WellSense AIoT"],["B.Eng.","Kasetsart University"]].map(([a,b])=><div key={b}><div className="font-display text-lg font-bold text-white">{a}</div><div className="mt-1 text-[10px] uppercase tracking-wider text-slate-500">{b}</div></div>)}</div>
    </div><div className="float hidden lg:block"><div className="glass relative rounded-3xl p-7 shadow-2xl shadow-cyan-950/20"><div className="absolute -right-8 -top-8 rounded-2xl border border-white/10 bg-[#0b111b]/90 p-3 shadow-xl"><Sparkles className="text-cyan-300" size={20}/></div><div className="mb-7 flex items-center gap-4"><div className="flex h-[72px] w-[72px] items-center justify-center rounded-2xl border border-cyan-300/20 bg-gradient-to-br from-cyan-300/20 to-violet-400/20 font-display text-2xl font-bold">TT</div><div><p className="font-display font-bold">Thanithpol</p><p className="text-xs text-slate-500">AI / Data Engineer</p></div></div><div className="space-y-3">{[["LLM / RAG","Agentic AI"],["Computer Vision","OCR · VQA"],["Data Engineering","PySpark · Databricks"],["AIoT","Edge · Sensors"]].map(([a,b])=><div key={a} className="flex items-center justify-between rounded-xl border border-white/[.06] bg-white/[.025] px-4 py-3"><span className="text-sm text-slate-200">{a}</span><span className="text-[10px] text-slate-500">{b}</span></div>)}</div></div></div></div></section>

    <section id="about" className="relative border-y border-white/[.06] bg-white/[.018]"><div className="mx-auto grid max-w-6xl gap-12 px-5 py-24 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><div><Label>01 / About</Label><h2 className="font-display text-4xl font-bold tracking-[-.04em] sm:text-5xl">Engineering mindset.<br/>AI toolkit.</h2></div><div><p className="text-xl leading-8 text-slate-300">My career started in environmental engineering and sustainability, then moved into AI/ML and data engineering. That combination gives me a systems mindset: understand the domain, structure the data, build the model, then turn it into a product.</p><div className="mt-10 grid gap-5 sm:grid-cols-3">{[["AI Engineering",BrainCircuit,"RAG, retrieval, reranking, tool-use, guardrails and multimodal AI."],["Data Engineering",Database,"ETL, SQL/PySpark, Delta Lake, Databricks and scalable workflows."],["AIoT Products",Cpu,"Sensors, edge devices, BLE and real-time user-facing systems."]].map(([title,Icon,text])=>{const I=Icon as typeof BrainCircuit;return <div key={title as string} className="rounded-2xl border border-white/[.07] bg-[#0a0f17] p-5"><I size={19} className="text-cyan-300"/><h3 className="mt-5 text-sm font-bold">{title as string}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{text as string}</p></div>})}</div></div></div></section>

    <section id="projects" className="relative mx-auto max-w-6xl px-5 py-24 lg:px-8"><div className="mb-12 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><Label>02 / Selected Work</Label><h2 className="font-display text-4xl font-bold tracking-[-.04em] sm:text-5xl">Projects that show<br/>how I build.</h2></div><LinkButton href="https://github.com/thanithpol2545">Explore all GitHub repositories</LinkButton></div><div className="grid gap-4 sm:grid-cols-2">{projects.map(p=><article key={p.n} className={`card-hover group rounded-3xl border border-white/[.07] bg-[#0a0f17] p-6 ${p.featured ? "sm:col-span-2 sm:p-8" : ""}`}><div className="flex items-start justify-between"><span className="font-display text-xs font-bold text-slate-600">{p.n}</span><span className="max-w-[60%] rounded-full border border-white/[.07] px-2.5 py-1 text-right text-[9px] font-bold uppercase tracking-wider text-slate-500">{p.type}</span></div><div className="mt-12 max-w-3xl"><h3 className="font-display text-2xl font-bold tracking-[-.025em] group-hover:text-cyan-100">{p.title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{p.desc}</p><p className="mt-5 text-[10px] font-medium uppercase leading-5 tracking-wider text-slate-400">{p.stack}</p><div className="mt-6"><LinkButton href={p.href}/></div></div></article>)}</div></section>

    <section id="moonwalk" className="border-y border-cyan-300/10 bg-gradient-to-b from-cyan-300/[.035] via-white/[.012] to-transparent"><div className="mx-auto max-w-6xl px-5 py-28 lg:px-8"><div className="grid gap-12 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div><Label>03 / Featured Case Study · Award Winning</Label><div className="flex flex-wrap items-center gap-3"><span className="rounded-full border border-cyan-300/20 bg-cyan-300/[.06] px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-cyan-200">1st Runner Up</span><span className="text-xs text-slate-500">WellSense AIoT Hackathon · 25 June 2026</span></div><h2 className="mt-5 font-display text-5xl font-bold tracking-[-.05em] sm:text-7xl">Moon Walk</h2><p className="mt-3 text-xl font-medium text-cyan-200">Walk with your own rhythm.</p><p className="mt-6 max-w-2xl text-base leading-7 text-slate-400">A clip-on sensor platform that turns an ordinary cane or walker into a smart mobility monitor. Moon Walk combines IMU motion sensing, cane-load feedback, BLE communication and an edge gateway to provide real-time biofeedback and rehabilitation insights.</p></div><div className="rounded-3xl border border-cyan-300/15 bg-[#07111b] p-6"><div className="flex items-center gap-4"><Trophy className="text-cyan-300" size={30}/><div><p className="text-xs font-bold uppercase tracking-widest text-cyan-200">Recognition</p><p className="mt-1 font-display text-2xl font-bold">1st Runner Up</p></div></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl border border-white/[.07] p-3"><p className="text-[9px] uppercase tracking-wider text-slate-500">Prize shown on award photo</p><p className="mt-1 font-display font-bold text-white">฿3,000</p></div><div className="rounded-xl border border-white/[.07] p-3"><p className="text-[9px] uppercase tracking-wider text-slate-500">Track</p><p className="mt-1 text-xs font-semibold text-white">Human Sensing for Wellness & E-Health</p></div></div></div></div>

      <div className="mt-16 grid gap-4 sm:grid-cols-3"><div className="rounded-3xl border border-white/[.07] bg-[#0a0f17] p-6"><p className="text-3xl font-display font-bold text-cyan-300">~35%</p><p className="mt-2 text-xs font-semibold text-white">reported error when patients estimate weight-bearing</p></div><div className="rounded-3xl border border-white/[.07] bg-[#0a0f17] p-6"><p className="text-3xl font-display font-bold text-cyan-300">~70%</p><p className="mt-2 text-xs font-semibold text-white">ankle-sprain recurrence rate shown in the project poster</p></div><div className="rounded-3xl border border-white/[.07] bg-[#0a0f17] p-6"><p className="text-3xl font-display font-bold text-cyan-300">3</p><p className="mt-2 text-xs font-semibold text-white">co-equal metrics: symmetry & rhythm, stick duty factor, session training load</p></div></div>

      <div className="mt-16"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Label>System Architecture</Label><h3 className="font-display text-3xl font-bold tracking-[-.03em]">Sensor → Gateway → Processing → Storage → Analytics</h3></div><span className="text-xs text-slate-600">End-to-end prototype architecture</span></div><div className="mt-8 grid gap-px overflow-hidden rounded-3xl border border-white/[.07] bg-white/[.07] md:grid-cols-5">{moonwalkLayers.map(([n,title,desc,Icon])=>{const I=Icon as typeof Activity;return <div key={n as string} className="bg-[#0a0f17] p-5"><div className="flex items-center justify-between"><span className="font-display text-xs font-bold text-slate-600">{n as string}</span><I size={18} className="text-cyan-300"/></div><h4 className="mt-7 font-display text-sm font-bold">{title as string}</h4><p className="mt-3 text-[11px] leading-5 text-slate-500">{desc as string}</p></div>})}</div></div>

      <div className="mt-12 grid gap-4 lg:grid-cols-2"><div className="rounded-3xl border border-white/[.07] bg-[#0a0f17] p-7"><div className="flex items-center gap-2"><Activity size={18} className="text-cyan-300"/><h3 className="font-display font-bold">Key Mobility Metrics</h3></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{[["Balance","left-right support balance"],["Cane Load","weight placed on the cane"],["Gait Rhythm","step cadence & walking regularity"]].map(([a,b])=><div key={a} className="rounded-2xl border border-white/[.06] p-4"><p className="text-xs font-bold text-white">{a}</p><p className="mt-1 text-[10px] leading-4 text-slate-500">{b}</p></div>)}</div></div><div className="rounded-3xl border border-white/[.07] bg-[#0a0f17] p-7"><div className="flex items-center gap-2"><ShieldCheck size={18} className="text-cyan-300"/><h3 className="font-display font-bold">Privacy-first Design</h3></div><p className="mt-5 text-sm leading-6 text-slate-500">The prototype emphasizes on-device sensing and feedback. The concept explicitly avoids requiring cloud storage for health data at the device-feedback stage, while the architecture supports optional cloud synchronization for later analytics.</p></div></div>

      <div className="mt-12 rounded-3xl border border-white/[.07] bg-[#0a0f17] p-7"><Label>Business Opportunity</Label><div className="grid gap-6 sm:grid-cols-3"><div><p className="font-display text-3xl font-bold text-white">150K/year</p><p className="mt-1 text-[10px] uppercase tracking-wider text-slate-500">Estimated Thailand rehab / walking-aid cases</p></div><div><p className="font-display text-3xl font-bold text-emerald-300">฿900M/year</p><p className="mt-1 text-[10px] uppercase tracking-wider text-slate-500">Estimated TAM</p></div><div><p className="font-display text-3xl font-bold text-cyan-300">฿12M/year</p><p className="mt-1 text-[10px] uppercase tracking-wider text-slate-500">Initial SOM</p></div></div><div className="mt-8 flex flex-wrap items-center gap-2 text-xs font-semibold text-slate-400"><span className="rounded-full border border-white/[.07] px-3 py-2">Hospital pilots</span><span className="text-slate-700">→</span><span className="rounded-full border border-white/[.07] px-3 py-2">Premium rehab service</span><span className="text-slate-700">→</span><span className="rounded-full border border-white/[.07] px-3 py-2">Patient subscription</span><span className="text-slate-700">→</span><span className="rounded-full border border-white/[.07] px-3 py-2">Cane / manufacturer partners</span></div></div>
      <p className="mt-6 text-[10px] leading-5 text-slate-600">Project poster notes describe Moon Walk as a wellness-awareness and rehabilitation-support concept, not a medical assessment.</p>
    </div></section>

    <section id="experience" className="border-y border-white/[.06] bg-white/[.018]"><div className="mx-auto max-w-5xl px-5 py-24 lg:px-8"><Label>04 / Experience</Label><h2 className="font-display text-4xl font-bold tracking-[-.04em] sm:text-5xl">From sustainability<br/>to AI engineering.</h2><div className="mt-14">{experiences.map(([date,role,company,desc])=><div key={role} className="grid grid-cols-[105px_1fr] gap-6 border-t border-white/[.07] py-7 sm:grid-cols-[160px_1fr]"><div className="text-[10px] font-bold uppercase tracking-wider text-cyan-300">{date}</div><div><h3 className="font-display text-lg font-bold">{role}</h3><p className="mt-1 text-xs font-semibold text-slate-500">{company}</p><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-500">{desc}</p></div></div>)}</div></div></section>

    <section id="skills" className="mx-auto max-w-6xl px-5 py-24 lg:px-8"><Label>05 / Toolkit</Label><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><h2 className="font-display text-4xl font-bold tracking-[-.04em] sm:text-5xl">Tools I use to ship.</h2><p className="max-w-md text-sm leading-6 text-slate-500">A cross-domain stack spanning AI, data, cloud, product development, edge computing and engineering.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-3xl border border-white/[.07] bg-white/[.07] sm:grid-cols-2">{skills.map(([title,text])=><div key={title} className="bg-[#0a0f17] p-7"><h3 className="font-display text-lg font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{text}</p></div>)}</div></section>

    <section className="mx-auto max-w-6xl px-5 pb-24 lg:px-8"><Label>06 / Recognition</Label><div className="grid gap-px overflow-hidden rounded-3xl border border-white/[.07] bg-white/[.07] sm:grid-cols-2 lg:grid-cols-4">{awards.map(([a,b,c,img])=><div key={a} className="bg-[#0a0f17] p-6"><Trophy size={18} className="text-cyan-300"/><div className="mt-5 font-display text-xl font-bold text-white">{a}</div><div className="mt-2 text-xs font-semibold text-slate-300">{b}</div>{img ? <img src={`/${img}`} alt={b} className="mt-3 w-full rounded-xl border border-white/[.07] object-cover"/> : <div className="mt-2 text-[10px] leading-4 text-slate-500">{c}</div>}</div>)}</div></section>

    <section id="contact" className="relative border-t border-white/[.06] bg-gradient-to-b from-cyan-400/[.04] to-transparent"><div className="mx-auto max-w-4xl px-5 py-32 text-center lg:px-8"><Label>07 / Contact</Label><h2 className="font-display text-5xl font-bold tracking-[-.055em] sm:text-7xl">Let&apos;s build something <span className="text-cyan-300">useful.</span></h2><p className="mx-auto mt-7 max-w-xl text-sm leading-7 text-slate-500 sm:text-base">Open to AI/ML, Data Engineering, AI Engineer and Full Stack opportunities where engineering fundamentals meet modern AI systems.</p><div className="mt-9 flex flex-wrap justify-center gap-3"><a href="mailto:thanipol2545@gmail.com" className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-bold text-slate-950"><Mail size={16}/> Email me</a><a href="https://www.linkedin.com/in/thanithpol-thiramongkolchai-2103151a8/" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-white/10 px-5 py-3 text-sm font-semibold"><Linkedin size={16}/> LinkedIn</a><a href="https://github.com/thanithpol2545" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-white/10 px-5 py-3 text-sm font-semibold"><Github size={16}/> GitHub</a></div></div></section>
    <footer className="border-t border-white/[.06] py-6 text-center text-[10px] uppercase tracking-widest text-slate-600">© {new Date().getFullYear()} Thanithpol Thiramongkolchai · Built with Next.js + Tailwind CSS</footer>
  </main>;
}
