import { ArrowDown, ArrowUpRight, BrainCircuit, Database, Github, Linkedin, Mail, Sparkles, Trophy, Cpu } from "lucide-react";
import { Navbar } from "@/components/navbar";

const projects = [
  { n: "01", title: "Hand Assessment AI", type: "Computer Vision · Healthcare", desc: "Video/webcam assessment for elderly rehabilitation. Tracks 21 hand landmarks, extracts speed/accuracy/quality features, compares left/right symmetry and estimates hand dominance and Learned Non-Use risk.", stack: "Python · OpenCV · MediaPipe · NumPy · SciPy · scikit-learn · Streamlit", href: "https://github.com/thanithpol2545/ai-vibe-coding-digital-aiding-4-aging-hackathon" },
  { n: "02", title: "Moon Walk — Smart Cane AIoT", type: "AIoT · Hackathon · Assistive Tech", desc: "1st Runner Up at the WellSense AIoT Hackathon. A clip-on sensing module turns an ordinary cane or walker into a smart mobility monitor for gait rhythm, balance and cane-load feedback.", stack: "Arduino Nano 33 BLE · LSM9DS1 IMU · Pressure Sensing · BLE · Arduino UNO Q · Supabase", href: "https://github.com/thanithpol2545", featured: true, imgs: ["moonwalk-project-1.jpg", "moonwalk-project-2.jpg"] },
  { n: "03", title: "Air Pollution & Fire Hotspots Analysis", type: "Data Science · Research", desc: "Thailand analysis connecting VIIRS hotspot activity with PM2.5, PM10, CO, NO2, SO2 and O3 using time-series, regional/provincial analysis, Pearson R, R² and p-values.", stack: "Python · Pandas · SciPy · scikit-learn · Excel · QGIS", href: "https://github.com/thanithpol2545/Combustion-Air-Pollutant-and-Fire-Hotspots-Analysis-in-Thailand" },
  { n: "04", title: "Nitrification Dynamics Simulator", type: "Environmental Engineering · Web", desc: "Interactive simulation project translating environmental-engineering process equations and nitrification dynamics into a usable web experience.", stack: "Python · Simulation · Web · Environmental Engineering", href: "https://github.com/thanithpol2545/nitrification-dynamics-simulator", imgs: ["nitrification.png"] },
  { n: "05", title: "Nan Flourish — Beyond Seasons", type: "Hackathon · Product", desc: "Hackathon project focused on building a digital experience around Nan and connecting technology, local context and user-facing product design.", stack: "Web · Product Design · Data · Hackathon", href: "https://sanae-nan.vercel.app", imgs: ["nan-flourish.png"] },
  { n: "06", title: "Siam Hack 4 Super AI", type: "AI · Hackathon", desc: "Interactive web app built with Google AI Studio / Gemini during the Siam Hack 4 Super AI hackathon.", stack: "Google AI Studio · Gemini · Vite · React", href: "https://sanae-siam-hack-4-super-ai.vercel.app", imgs: ["siam-hack.png"] },
];

const skills = [
  ["LLM & AI Applications", "RAG · Hybrid Retrieval · Reranking · Agentic / Tool Use · Prompt Engineering · Guardrails · Thai NLP · LLM Evaluation"],
  ["ML & Deep Learning", "PyTorch · Hugging Face Transformers · scikit-learn · LightGBM · XGBoost · Computer Vision · OCR · ASR · VQA · Time Series"],
  ["Data Engineering", "Python · SQL · Pandas · PySpark · ETL · Delta Lake · Medallion Architecture · Databricks · Lakeflow · Jobs · Unity Catalog"],
  ["Product & Development", "Next.js · React · TypeScript · Tailwind CSS · Streamlit · Power BI · Git · GitHub · Docker · Linux"],
  ["AIoT & Edge", "Arduino · Arduino UNO Q · Raspberry Pi · Jetson Nano · IMU · BLE · IoT sensor networks · Edge AI"],
  ["Engineering & Sustainability", "GHG Protocol · Scope 1–3 · CFO · CFP · ESG · QGIS · AutoCAD · Environmental Engineering"],
];

const experiences = [
  ["2025", "Business Development Associate", "Zeroboard (Thailand) Co., Ltd.", "Supported ESG and carbon-accounting projects, GHG Protocol Scope 1–3, Carbon Footprint for Organization and Product, and data-driven sustainability initiatives."],
  ["2025", "Digital & Sustainability Officer", "MDT Manufacturing", "Built barcode/data-collection workflows, centralized ISO data, supported CFO/CFP reporting and KPI dashboards."],
  ["2024", "Site Engineer Intern", "Origin Property Public Co.", "Supported construction-site engineering and building-system coordination at The Origin Plug & Play Ramintra."],
  ["2022", "Research Assistant", "Kasetsart University · Faculty of Agriculture", "Worked with IoT sensors and experimental data for indoor smart-farming research."],
];

const awards = [
  ["Top 21", "AI Benchmark 2026 · LLM Trustworthiness Challenge", "11th place · Team E20 · 91 teams / 194 participants"],
  ["1st Runner Up", "WellSense AIoT Hackathon · Super AI Engineer S6", "", "moonwalk-award.jpg"],
  ["180 / 10,000+", "Super AI Engineer Season 6 · AIAT", "Selected for the national AI engineering program"],
  ["Associate Engineer", "Council of Engineers Thailand", "Environmental Engineering professional license"],
];

function Label({ children }: { children: React.ReactNode }) { return <p className="mb-4 text-base font-bold uppercase tracking-[.22em] text-cyan-300">{children}</p>; }
function LinkButton({ href, children = "View project" }: { href: string; children?: React.ReactNode }) { return <a href={href} target={href.startsWith("http") ? "_blank" : undefined} rel={href.startsWith("http") ? "noreferrer" : undefined} className="inline-flex items-center gap-1.5 text-base font-semibold text-cyan-200 transition hover:text-white">{children}<ArrowUpRight size={14}/></a>; }

export default function Home() {
  return <main id="top" className="noise relative overflow-hidden"><Navbar /><div className="pointer-events-none absolute inset-x-0 top-0 h-[760px] grid-fade" /><div className="pointer-events-none absolute -top-48 left-1/2 h-[560px] w-[560px] -translate-x-1/2 rounded-full bg-cyan-400/[.07] blur-[120px]" />
    <section className="relative mx-auto flex min-h-screen max-w-6xl items-center px-5 pb-20 pt-32 lg:px-8"><div className="grid w-full gap-14 lg:grid-cols-[1.35fr_.65fr] lg:items-center"><div>
      <div className="mb-7 inline-flex items-center gap-2 rounded-full border border-cyan-300/15 bg-cyan-300/[.05] px-3 py-1.5 text-base font-semibold text-cyan-100"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-400"/> AI / ML · DATA · AIoT · FULL STACK</div>
      <h1 className="max-w-4xl font-display text-5xl font-bold leading-[.98] tracking-[-.055em] text-white sm:text-7xl lg:text-[88px]">Building intelligent products <span className="bg-gradient-to-r from-cyan-300 via-sky-300 to-violet-300 bg-clip-text text-transparent">from data to deployment.</span></h1>
      <p className="mt-8 max-w-2xl text-base leading-7 text-white sm:text-lg">I&apos;m Thanithpol Thiramongkolchai — an Environmental Engineer turned AI/ML Engineer. I build LLM/RAG systems, agentic pipelines, computer-vision applications, data platforms and AIoT products.</p>
      <div className="mt-9 flex flex-wrap gap-3"><a href="#projects" className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-base font-bold text-slate-950 transition hover:-translate-y-0.5 hover:bg-cyan-100">Explore my work <ArrowDown size={16}/></a><a href="mailto:thanipol2545@gmail.com" className="inline-flex items-center gap-2 rounded-full border border-white/10 px-5 py-3 text-base font-semibold text-white transition hover:-translate-y-0.5 hover:border-cyan-300/30"><Mail size={16}/> Contact</a></div>
    </div><div className="float hidden lg:block"><div className="glass relative rounded-3xl p-7 shadow-2xl shadow-cyan-950/20"><div className="absolute -right-8 -top-8 rounded-2xl border border-white/10 bg-[#0b111b]/90 p-3 shadow-xl"><Sparkles className="text-cyan-300" size={20}/></div><div className="mb-7 flex items-center gap-4"><img src="/profile.jpg" alt="Thanithpol Thiramongkolchai" className="h-[72px] w-[72px] rounded-2xl border border-cyan-300/20 object-cover"/><div><p className="font-display font-bold">Thanithpol</p><p className="text-base text-white">AI / Data Engineer</p></div></div><div className="space-y-3">{[["LLM / RAG","Agentic AI"],["Computer Vision","OCR · VQA"],["Data Engineering","PySpark · Databricks"],["AIoT","Edge · Sensors"]].map(([a,b])=><div key={a} className="flex items-center justify-between rounded-xl border border-white/[.06] bg-white/[.025] px-4 py-3"><span className="text-base text-white">{a}</span><span className="text-base text-white">{b}</span></div>)}</div></div></div></div></section>

    <section id="about" className="relative border-y border-white/[.06] bg-white/[.018]"><div className="mx-auto grid max-w-6xl gap-12 px-5 py-24 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><div><Label>01 / About</Label><h2 className="font-display text-4xl font-bold tracking-[-.04em] sm:text-5xl">Engineering mindset.<br/>AI toolkit.</h2><img src="/about-photo.jpg" alt="Thanithpol Thiramongkolchai" className="mt-8 w-full max-w-sm rounded-3xl border border-white/[.07] object-cover"/></div><div><p className="text-xl leading-8 text-white">My career started in environmental engineering and sustainability, then moved into AI/ML and data engineering. That combination gives me a systems mindset: understand the domain, structure the data, build the model, then turn it into a product.</p><div className="mt-10 grid gap-5 sm:grid-cols-3">{[["AI Engineering",BrainCircuit,"RAG, retrieval, reranking, tool-use, guardrails and multimodal AI."],["Data Engineering",Database,"ETL, SQL/PySpark, Delta Lake, Databricks and scalable workflows."],["AIoT Products",Cpu,"Sensors, edge devices, BLE and real-time user-facing systems."]].map(([title,Icon,text])=>{const I=Icon as typeof BrainCircuit;return <div key={title as string} className="rounded-2xl border border-white/[.07] bg-[#0a0f17] p-5"><I size={19} className="text-cyan-300"/><h3 className="mt-5 text-base font-bold">{title as string}</h3><p className="mt-2 text-base leading-5 text-white">{text as string}</p></div>})}</div></div></div></section>

    <section id="projects" className="relative mx-auto max-w-6xl px-5 py-24 lg:px-8"><div className="mb-12 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><Label>02 / Selected Work</Label><h2 className="font-display text-4xl font-bold tracking-[-.04em] sm:text-5xl">Projects that show<br/>how I build.</h2></div><LinkButton href="https://github.com/thanithpol2545">Explore all GitHub repositories</LinkButton></div><div className="grid gap-4 sm:grid-cols-2">{projects.map(p=><article key={p.n} className={`card-hover group rounded-3xl border border-white/[.07] bg-[#0a0f17] p-6 ${p.featured ? "sm:col-span-2 sm:p-8" : ""}`}><div className="flex items-start justify-between"><span className="font-display text-base font-bold text-white">{p.n}</span><span className="max-w-full rounded-full border border-white/[.07] px-3 py-1 text-base font-bold uppercase tracking-wider text-white">{p.type}</span></div><div className="mt-12 max-w-3xl"><h3 className="font-display text-2xl font-bold tracking-[-.025em] group-hover:text-cyan-100">{p.title}</h3><p className="mt-3 text-base leading-6 text-white">{p.desc}</p><p className="mt-5 text-base font-medium uppercase leading-5 tracking-wider text-white">{p.stack}</p><div className="mt-6"><LinkButton href={p.href}/></div>{p.imgs ? <div className={`mt-8 grid gap-4 ${p.imgs.length > 1 ? "sm:grid-cols-2" : ""}`}>{p.imgs.map(img=><img key={img} src={`/${img}`} alt={p.title} className="w-full rounded-2xl border border-white/[.07] object-cover"/>)}</div> : null}</div></article>)}</div></section>

    <section id="experience" className="border-y border-white/[.06] bg-white/[.018]"><div className="mx-auto max-w-5xl px-5 py-24 lg:px-8"><Label>03 / Experience</Label><h2 className="font-display text-4xl font-bold tracking-[-.04em] sm:text-5xl">From sustainability<br/>to AI engineering.</h2><div className="mt-14">{experiences.map(([date,role,company,desc])=><div key={role} className="grid grid-cols-[105px_1fr] gap-6 border-t border-white/[.07] py-7 sm:grid-cols-[160px_1fr]"><div className="text-base font-bold uppercase tracking-wider text-cyan-300">{date}</div><div><h3 className="font-display text-lg font-bold">{role}</h3><p className="mt-1 text-base font-semibold text-white">{company}</p><p className="mt-3 max-w-2xl text-base leading-6 text-white">{desc}</p></div></div>)}</div></div></section>

    <section id="skills" className="mx-auto max-w-6xl px-5 py-24 lg:px-8"><Label>04 / Toolkit</Label><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><h2 className="font-display text-4xl font-bold tracking-[-.04em] sm:text-5xl">Tools I use to ship.</h2><p className="max-w-md text-base leading-6 text-white">A cross-domain stack spanning AI, data, cloud, product development, edge computing and engineering.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-3xl border border-white/[.07] bg-white/[.07] sm:grid-cols-2">{skills.map(([title,text])=><div key={title} className="bg-[#0a0f17] p-7"><h3 className="font-display text-lg font-bold">{title}</h3><p className="mt-3 text-base leading-6 text-white">{text}</p></div>)}</div></section>

    <section id="recognition" className="mx-auto max-w-6xl px-5 pb-24 lg:px-8"><Label>05 / Recognition</Label><div className="grid gap-px overflow-hidden rounded-3xl border border-white/[.07] bg-white/[.07] sm:grid-cols-2 lg:grid-cols-4">{awards.map(([a,b,c,img])=><div key={a} className="bg-[#0a0f17] p-6"><Trophy size={18} className="text-cyan-300"/><div className="mt-5 font-display text-xl font-bold text-white">{a}</div><div className="mt-2 text-base font-semibold text-white">{b}</div>{img ? <img src={`/${img}`} alt={b} className="mt-3 w-full rounded-xl border border-white/[.07] object-cover"/> : <div className="mt-2 text-base leading-4 text-white">{c}</div>}</div>)}</div></section>

    <section id="contact" className="relative border-t border-white/[.06] bg-gradient-to-b from-cyan-400/[.04] to-transparent"><div className="mx-auto max-w-4xl px-5 py-32 text-center lg:px-8"><Label>06 / Contact</Label><h2 className="font-display text-5xl font-bold tracking-[-.055em] sm:text-7xl">Let&apos;s build something <span className="text-cyan-300">useful.</span></h2><p className="mx-auto mt-7 max-w-xl text-base leading-7 text-white sm:text-base">Open to AI/ML, Data Engineering, AI Engineer and Full Stack opportunities where engineering fundamentals meet modern AI systems.</p><div className="mt-9 flex flex-wrap justify-center gap-3"><a href="mailto:thanipol2545@gmail.com" className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-base font-bold text-slate-950"><Mail size={16}/> Email me</a><a href="https://www.linkedin.com/in/thanithpol-thiramongkolchai-2103151a8/" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-white/10 px-5 py-3 text-base font-semibold"><Linkedin size={16}/> LinkedIn</a><a href="https://github.com/thanithpol2545" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-white/10 px-5 py-3 text-base font-semibold"><Github size={16}/> GitHub</a></div></div></section>
    <footer className="border-t border-white/[.06] py-6 text-center text-base uppercase tracking-widest text-white">© {new Date().getFullYear()} Thanithpol Thiramongkolchai</footer>
  </main>;
}
